/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedHuespedesRouteImport } from './routes/_authenticated/huespedes'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPropiedadesIndexRouteImport } from './routes/_authenticated/propiedades.index'
import { Route as AuthenticatedPropiedadesIdRouteImport } from './routes/_authenticated/propiedades.$id'
import { Route as AuthenticatedReservasIndexRouteImport } from './routes/_authenticated/reservas.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHuespedesRoute = AuthenticatedHuespedesRouteImport.update({
  id: '/huespedes',
  path: '/huespedes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropiedadesIndexRoute =
  AuthenticatedPropiedadesIndexRouteImport.update({
    id: '/propiedades/',
    path: '/propiedades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropiedadesIdRoute =
  AuthenticatedPropiedadesIdRouteImport.update({
    id: '/propiedades/$id',
    path: '/propiedades/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservasIndexRoute =
  AuthenticatedReservasIndexRouteImport.update({
    id: '/reservas/',
    path: '/reservas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades/$id': typeof AuthenticatedPropiedadesIdRoute
  '/propiedades/': typeof AuthenticatedPropiedadesIndexRoute
  '/reservas/': typeof AuthenticatedReservasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades/$id': typeof AuthenticatedPropiedadesIdRoute
  '/propiedades': typeof AuthenticatedPropiedadesIndexRoute
  '/reservas': typeof AuthenticatedReservasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/huespedes': typeof AuthenticatedHuespedesRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/propiedades/$id': typeof AuthenticatedPropiedadesIdRoute
  '/_authenticated/propiedades/': typeof AuthenticatedPropiedadesIndexRoute
  '/_authenticated/reservas/': typeof AuthenticatedReservasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/finanzas'
    | '/huespedes'
    | '/oportunidades'
    | '/panel'
    | '/propiedades/$id'
    | '/propiedades/'
    | '/reservas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/finanzas'
    | '/huespedes'
    | '/oportunidades'
    | '/panel'
    | '/propiedades/$id'
    | '/propiedades'
    | '/reservas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendario'
    | '/_authenticated/finanzas'
    | '/_authenticated/huespedes'
    | '/_authenticated/oportunidades'
    | '/_authenticated/panel'
    | '/_authenticated/propiedades/$id'
    | '/_authenticated/propiedades/'
    | '/_authenticated/reservas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/huespedes': {
      id: '/_authenticated/huespedes'
      path: '/huespedes'
      fullPath: '/huespedes'
      preLoaderRoute: typeof AuthenticatedHuespedesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propiedades/': {
      id: '/_authenticated/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof AuthenticatedPropiedadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propiedades/$id': {
      id: '/_authenticated/propiedades/$id'
      path: '/propiedades/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof AuthenticatedPropiedadesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas/': {
      id: '/_authenticated/reservas/'
      path: '/reservas'
      fullPath: '/reservas/'
      preLoaderRoute: typeof AuthenticatedReservasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedHuespedesRoute: typeof AuthenticatedHuespedesRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPropiedadesIdRoute: typeof AuthenticatedPropiedadesIdRoute
  AuthenticatedPropiedadesIndexRoute: typeof AuthenticatedPropiedadesIndexRoute
  AuthenticatedReservasIndexRoute: typeof AuthenticatedReservasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedHuespedesRoute: AuthenticatedHuespedesRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPropiedadesIdRoute: AuthenticatedPropiedadesIdRoute,
  AuthenticatedPropiedadesIndexRoute: AuthenticatedPropiedadesIndexRoute,
  AuthenticatedReservasIndexRoute: AuthenticatedReservasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
